<<<<<<< HEAD
=======
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

>>>>>>> e214aac40503b2e28c5bcc73b7c91726014c7e35
groups:
  - name: devs
    reviewers: 1
    usernames:
      - rileykarson
      - slevenick
      - c2thorn
      - scottsuarez
      - melinath
<<<<<<< HEAD
      - megan07
=======
>>>>>>> e214aac40503b2e28c5bcc73b7c91726014c7e35
      - shuyama1
