name: "Pull Request Reviewer"
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  test:
    if: ${{ github.actor != 'modular-magician' }}
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v2
    - uses: uesteibar/reviewer-lottery@5531ef7fe55d814c8f8fbab12de4ff74d15b41ed
=======
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: uesteibar/reviewer-lottery@c291d74388da1cb583aff994b8be945e8eefbcd5 # v3.1.0
>>>>>>> e214aac40503b2e28c5bcc73b7c91726014c7e35
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
